apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: my-validating-webhook
webhooks:
- name: my-validating-webhook.example.com
  rules:
  - apiGroups: ["*"]
    apiVersions: ["*"]
    operations: ["*"]
    resources: ["*/*"]
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  clientConfig:
    service:
      namespace: default
      name: my-validating-webhook-service