apiVersion: v1
kind: Service
metadata:
  name: kubescape-webhook-svc
  labels:
    app: kubescape-webhook-svc
  creationTimestamp: null
  spec:
    ports:
    - protocol: TCP
      port: 443
      targetPort: 9000
    selector:
      app: kubescape-webhook
status:
  loadBalancer: {}     